from configparser import ConfigParser, ExtendedInterpolation
from itertools import chain
from pathlib import Path
from jinja2 import Environment, FileSystemLoader, select_autoescape
from urllib.request import urlopen


class Table:
    """ This class makes it easier to generate tables in jinja templates
    """
    def __init__(self, data, cols, transpose=False):
        self.data = [*data]
        self.ncols = cols
        self.transpose = transpose

        if not self.data:
            self.width = 0
            self.blank = ""
            self.nrows = 0
            return

        if isinstance(self.data[0], str):
            self.width = max(map(len, self.data))
            self.blank = ""
        else:
            self.width = max(map(len, [d[0] for d in self.data]))
            self.blank = tuple([""]*len(self.data[0]))
        rows, r = divmod(len(data), cols)
        self.nrows = rows + 1 if r else rows

    def __len__(self):
        return len(self.data)

    def __getitem__(self, key):
        if self.transpose:
            idx = key[0] * self.nrows + key[1]
        else:
            idx = key[0] * self.ncols + key[1]
        return self.data[idx] if idx < len(self) else self.blank

    @property
    def cols(self):
        return range(self.ncols)

    @property
    def rows(self):
        return range(self.nrows)


# Read the current team information from configuration file
base_dir = Path(__file__).resolve().parent
repo_root = base_dir.parent.parent

team = ConfigParser(interpolation=ExtendedInterpolation())
team.optionxform = lambda x: x
team.read(base_dir / "team.ini")

# Environment for applying templates
env = Environment(
    loader=FileSystemLoader(str(base_dir)),
    autoescape=select_autoescape(),
    trim_blocks=True,
    lstrip_blocks=True
)

# Collect names for the team page
if team.has_section("contributing-individual"):
    extra = [*team["contributing-individual"].items()]
else:
    extra = []
exclude = [*team["active-team"].keys()] + [*team["inactive-team"].keys()]
extra = [e for e in extra if e[0] not in exclude]

# Create team webpage from template
team_rst = env.get_template("team.rst_t")
with open(base_dir / "team.rst", "w") as fh:
    fh.write(team_rst.render(
        team=team,
        atable=Table(team["active-team"].items(), 4),
        itable=Table(team["inactive-team"].items(), 4),
        ctable=Table(extra, 3, transpose=True)
    ))

institution_set = set(chain(
    team["dev-institution"].items(), team["contributing-institution"].items()
))
institution_set = list(institution_set)
institution_set.sort(key=lambda x: x[0])

# individual_set = dict(team["contributing-individual"].items())
# individual_set.update(team["active-team"].items())
individual_set = dict(team["active-team"].items())
individual_set.update(team["inactive-team"].items())
individual_set = list(individual_set.items())
individual_set.sort(key=lambda x: x[0].split()[-1])


def _rst_link(text, url):
    return f"`{text} <{url}>`_" if url else text


with open(repo_root / "AUTHORS.rst", "w") as fh:
    fh.write(
        ".. This file is generated by docs/source/team.py.\n"
        "   DO NOT EDIT DIRECTLY\n\n"
        "Authors\n"
        "=======\n\n"
        "Institutions\n"
        "------------\n\n"
    )
    for name, url in institution_set:
        fh.write(f"* {_rst_link(name, url)}\n")

    fh.write("\nTeam members\n------------\n\n")
    for name, links in individual_set:
        website = links.split(",")[0]
        fh.write(f"* {_rst_link(name, website)}\n")