[a]
# A section for short links
gh: https://github.com
lat : http://lattes.cnpq.br

[dev-institution]
# Use format
# institution: institution_website
#
# then complete a section with:
#
# [institution]
# department: website
University of São Paulo: https://www.usp.br/
State University of Campinas: https://www.unicamp.br/

[University of São Paulo]
Escola Politécnica da USP: https://www.poli.usp.br/
Núcleo de Dinâmica e Fluidos: https://ndf.poli.usp.br/
Research Centre for Greenhouse Gas Innovation: https://sites.usp.br/rcgi/br/home/
; Department of Earth Science and Engineering: ${a:icl}/ese

[State University of Campinas]
School of Civil Engineering, Architecture and Urban Planning: https://www.fecfau.unicamp.br/

[active-team]
# Use format
# name : personal-webpage
# Note that if you add your name here you should also add a picture of yourself
# in /docs/source/images.
Alexandre Olender: ${a:lat}/4631937820599808
Ruben Andres Salas: ${a:lat}/3294895625466892
Daiane I. Dolci: ${a:lat}/1341115679564843
Romildo Soares Jr: ${a:lat}/7845811382749340
Jéssica Sales P. dos Santos: ${a:lat}/7928058746144881
Paula Neves de Araújo: ${a:lat}/1029138492596274
Thiago Dias dos Santos: ${a:lat}/3618128074442916
Bruno Souza Carmo: ${a:lat}/8129545750278083

[inactive-team]
Keith J. Roberts: https://www.keithroberts.site/
Lucas Franceschini: ${a:lat}/4921110587510112
Eduardo Moscatelli de Souza: https://scholar.google.com/citations?user=Z2hqFC8AAAAJ&hl=pt-BR

[contributing-institution]
University of São Paulo: https://www.usp.br/
