name: Test Demos. Notebook support incoming

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  demo-tests:
    name: Demo tests
    runs-on: self-hosted
    # Runs on all pushes and pull requests for quick feedback

    container:
      image: firedrakeproject/firedrake:2025.4.1
      options: --user root  # Ensures it can install packages if needed

    steps:
    - name: Pre-run cleanup
      # Make sure the current directory is empty
      run: find . -delete

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Spyro
      uses: ./.github/actions/setup

    - name: Running demo tests
      run: |
        make clean
        mpiexec -n 6 pytest tests/demo_tests/test_acoustic_camembert_demo.py
        mpiexec -n 6 pytest tests/demo_tests/test_acoustic_layer_demo.py
        pytest tests/demo_tests/test_acoustic_marmousi_forward_propagation.py

    - name: Post-run cleanup
      if: always()
      run: find . -delete
