name: Run lint

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Install linter
        run: |
          pip install flake8 pylint
      - name: Lint codebase
        run: |
          make lint GITHUB_ACTIONS_FORMATTING=1
