# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Running serial tests
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          pytest --cov-report=xml --cov=spyro test/
    - name: Running parallel 3D forward test
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 6 pytest test_3d/test_hexahedral_convergence.py
          mpiexec -n 6 pytest test_parallel/test_forward.py
          mpiexec -n 6 pytest test_parallel/test_fwi.py
          mpiexec -n 6 pytest test_parallel/test_forward_supershot.py
          mpiexec -n 2 pytest test_parallel/test_parallel_io.py
          mpiexec -n 3 pytest test_parallel/test_supershot_grad.py
          mpiexec -n 2 pytest test_parallel/test_forward_multiple_serial_shots.py
    - name: Covering parallel 3D forward test
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 6 pytest --cov-report=xml --cov-append --cov=spyro test_3d/test_hexahedral_convergence.py
    - name: Covering parallel forward test
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 6 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_forward.py
    - name: Covering parallel fwi test
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 6 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_fwi.py
    - name: Covering parallel supershot test
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 6 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_forward_supershot.py
    - name: Covering parallel io test
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 2 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_parallel_io.py
    - name: Covering parallel supershot grad test
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 3 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_supershot_grad.py
    - name: Covering spatially parallelized shots in serial
      continue-on-error: true
      run: |
          source /home/olender/Firedrakes/newest3/firedrake/bin/activate
          mpiexec -n 2 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_forward_multiple_serial_shots.py
    # - name: Running serial tests for adjoint
    #   run: |
    #       source /home/olender/Firedrakes/main/firedrake/bin/activate
    #       pytest -n 10 --cov-report=xml --cov-append --cov=spyro test_ad/
    # - name: Running parallel tests
    #   run: |
    #       source /home/olender/Firedrakes/main/firedrake/bin/activate
    #       cp /home/olender/Testing_files/velocity_models/* velocity_models/
    #       cp /home/olender/Testing_files/meshes/* meshes/
    #       mpiexec -n 10 pytest test_parallel/test_forward.py
    # - name: Covering parallel tests
    #   continue-on-error: true
    #   run: |
    #       source /home/olender/Firedrakes/main/firedrake/bin/activate
    #       cp /home/olender/Testing_files/velocity_models/* velocity_models/
    #       cp /home/olender/Testing_files/meshes/* meshes/
    #       mpiexec -n 10 pytest --cov-report=xml --cov-append --cov=spyro test_parallel/test_forward.py
    # - name: Covering parallel 3D forward test
    #   continue-on-error: true
    #   run: |
    #       source /home/olender/Firedrakes/main/firedrake/bin/activate
    #       cp /home/olender/Testing_files/velocity_models/* velocity_models/
    #       cp /home/olender/Testing_files/meshes/* meshes/
    #       mpiexec -n 10 pytest --cov-report=xml --cov-append --cov=spyro test_3d/test_forward_3d.py 
    - name: Uploading coverage to Codecov
      run: export CODECOV_TOKEN="057ec853-d7ea-4277-819b-0c5ea2f9ff57" && bash <(curl -s https://codecov.io/bash)

